name: Delete Preview Theme

on:
  pull_request:
    types: [closed]
    branches-ignore: ["github-action/**"]

jobs:
  delete:
    runs-on: ubuntu-latest
    env:
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
      SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}
    steps:
      - uses: actions/checkout@v4
      - uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 50 # Shopify preview environment name cannot be more than 50 chars
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
          cache: "yarn"
      - name: Install packages
        run: yarn install
      - name: Delete theme
        run: npx shopkeeper theme delete --theme ${{ env.GITHUB_REF_NAME_SLUG_URL }} --force
